#!/bin/sh
# Served at https://lunarfs.com/install.sh
# Stable front door that forwards to the latest LunarFS release installer.
# The actual installer is generated by cargo-dist and published to each GitHub
# release as devdropbox-installer.sh. This shim always resolves /releases/latest/
# so it requires no update between releases.
#
# Usage:
#   curl --proto '=https' --tlsv1.2 -LsSf https://lunarfs.com/install.sh | sh
#   curl --proto '=https' --tlsv1.2 -LsSf https://lunarfs.com/install.sh | sh -s -- --help

set -e
set -u

# Enable pipefail when the shell supports it (bash, dash w/ recent versions).
# Using a subshell test avoids a fatal error on strict POSIX sh.
# shellcheck disable=SC3040
(set -o pipefail 2>/dev/null) && set -o pipefail

INSTALLER_URL="https://github.com/lunarfs/lunarfs/releases/latest/download/devdropbox-installer.sh"

if ! command -v curl > /dev/null 2>&1; then
    echo "error: curl is required to install LunarFS but was not found" >&2
    exit 1
fi

exec curl --proto '=https' --tlsv1.2 -LsSf "$INSTALLER_URL" | sh -s -- "$@"
